import { DeveloperRepo } from '../developer/developerRepo';
import { DeveloperModel } from '../developer/model';
import { textUtils } from '../utils/textUtils';

const developers = [
  'NIS America Inc.',
  'Nacon',
  'Paradox Interactive AB',
  '2K Games',
  'Fulqrum Publishing',
  'Idea Factory International',
  'Kalypso Media Digital',
  'tinyBuild',
  'Microids',
  'Daedalic Entertainment',
  'Fruitbat Factory',
  'indie.io',
  'Iceberg Interactive',
  'H2 Interactive Co. Ltd.',
  'Medibang Inc',
  'Dear Villagers',
  'Stardock Entertainment',
  'Night Dive Studios',
  'Headup Games',
  'Strategy First',
  'American Mythology',
  'Nomad Games',
  'GrabTheGames',
  'GIANTS Software GmbH',
  'astragon Entertainment GmbH',
  'Aerosoft GmbH',
  'HandyGames',
  'TheGameCreators',
  'Assemble Entertainment',
  'PlayWay S.A.',
  'Viva Media',
  'Ziggurat Interactive',
  'Gamera Games',
  'LucasArts',
  'PQube',
  'Shiravune',
  'Piko Interactive LLC',
  'Bigben Interactive',
  'CI Games',
  'Funcom',
  'GameMill Entertainment',
  'Good Shepherd Entertainment',
  'Goblinz Publishing',
  'NEOWIZ',
  'Expansive Worlds',
  'Topware Interactive',
  'Grey Alien Games',
  'Kasedo Games',
  'Michael La Ronn',
  'Akupara Games',
  'Sticky Rice Games',
  'Wired Productions',
  'HexWar Games',
  'MumboJumbo',
  'Techland Publishing',
  'Twin Sails Interactive',
  'Forever Entertainment S. A.',
  'Maple Whispering Limited',
  'Private Division',
  'Untold Tales',
  'Avalon Digital',
  'Digerati Distribution',
  'Minimol Games',
  'KEMCO',
  'WhisperGames',
  'FireFly Studios',
  'Marmalade Game Studio Ltd',
  'Thunderful Publishing',
  'Beamdog',
  'FeelThere',
  'Libredia',
  'META Publishing',
  'Milestone S.r.l.',
  'Excalibur',
  'Tonguç Bodur',
  'Tripwire Interactive',
  'Valusoft Cosmi',
  '2P Games',
  'Hooded Horse',
  'Team17',
  'Digital Tribe',
  'Fireshine Games',
  'HeroCraft',
  'Kepler Interactive',
  'NBM PUBLISHING',
  'NeocoreGames',
  'Ravenscourt',
  '10tons Ltd',
  'Flying Interactive',
  'Graffiti Games',
  'Karl Drinkwater',
  'Klabater',
  'Meridian4',
  'Ultimate Games S.A.',
  'YAW Studios',
  'Yogscast Games',
  'rokaplay',
  'Arcen Games LLC',
  'Bleem!',
  'Chorus Worldwide Games',
  'HypeTrain Digital',
  'InvertMouse',
  'Might and Delight',
  'DANGEN Entertainment',
  'GSC Game World',
  'Mens Sana Interactive',
  'Ripstone',
  'Little Green Men Games',
  'Phoenix Online Publishing',
  'Playstack',
  'WayForward',
  'Whitethorn Digital',
  'roseVeRte',
  'Boss Fight Books',
  'CINEMAX s.r.o.',
  'IO Interactive A/S',
  'N3V Games',
  'Secret Mode',
  'Wales Interactive',
  'Bandai Namco Entertainment Inc.',
  'Behaviour Interactive Inc.',
  'Crytivo',
  'Natsume Inc.',
  'Systemic Reaction',
  '34BigThings srl',
  '704 Games Company',
  'Anvil Game Studios',
  'CITY CONNECTION',
  'City Interactive S.A.',
  'Digital Dreams Entertainment',
  'Frozenbyte',
  'Games Operators',
  'Jetdogs Studios',
  'Kalypso Media',
  'Kerberos Productions Inc.',
  'KishMish Games',
  'Qumaron',
  'Walter Machado',
  'exosyphen studios',
  'Blowfish Studios',
  'DreadXP',
  'Firesquid',
  'Gotcha Gotcha Games Inc',
  'IMGN.PRO',
  'Ivanovich Games',
  'JoyBits Ltd.',
  'Survios',
  'The Irregular Corporation',
  'Zojoi',
  '2x2 Games',
  'Aldorlea Games',
  'Another Indie',
  'Classics Digital',
  'Movie Games S.A.',
  'Oddworld Inhabitants',
  'PID Games',
  'QUBYTE INTERACTIVE',
  'Sleepy Duck',
  'Toge Productions',
  'Acram Digital',
  'Coatsink',
  'Coffee Stain Studios',
  'Dovetail Games - Trains',
  'FobTi interactive',
  'Frontier Foundry',
  'Gearbox Publishing',
  'Green Sauce Games',
  'HeroCraft PC',
  'KONAMI',
  'Nival',
  'Numskull Games',
  'Playtonic Friends',
  'Robot Entertainment',
  'Source Byte Sp. z o.o.',
  'id Software',
  '🚀 Raiser Games',
  'ARTE France',
  'Abyssal Studios',
  'Alternative Software Ltd',
  'Axis Game Factory LLC',
  'Black Shell Media',
  'Bonus Stage Publishing',
  'Choice Provisions',
  'EnsenaSoft',
  'Frozen District',
  'Henteko Doujin',
  'Lonely Troops',
  'MoeNovel',
  'Neon Doctrine',
  'Red Hook Studios',
  'Serenity Forge',
  'Telltale',
  'Yooreka Studio',
  'indienova',
  '2K',
  'Big Sugar',
  'Cleverweek',
  'Clickteam',
  'Dark Wave Comics',
  'Doyoyo Games',
  'Endless Loop Studios',
  'Fast Travel Games',
  'IndieArk',
  'Kitfox Games',
  'Milkstone Studios',
  'Motion Twin',
  'New Blood Interactive',
  'Nukearts Studio',
  'Resolution Games',
  'Retroism',
  'Revolution Software Ltd',
  'Rogue Games Inc.',
  'Rogueside',
  'Saber Interactive Inc',
  'SimBin',
  'Warhorse Studios',
  'Activision',
  'Blazing Griffin',
  'BlueLine Games',
  'Cheesecake Dev',
  'Dire Wolf',
  'DrinkBox Studios',
  'Duality Games',
  'Eleventh Hour Games',
  'Flazm',
  'Fractale',
  'Gamious',
  'Gearbox Publishing San Francisco',
  'Hook',
  'Hyperstrange',
  'Ironhide Game Studio',
  'Just For Games',
  'Kinda Brave',
  'Midjiwan AB',
  'Mimimi Games',
  'Noodlecake',
  'NovaLogic',
  'Overseer Games',
  'PM Studios inc.',
  'Pinel Games',
  'SOFTSTAR Entertainment',
  'Schell Games',
  'Sigma Team Inc.',
  'Spawn Digital',
  'Stately Snail',
  'SuperGG.com',
  'Surefire.Games',
  'Tactical Adventures',
  'Tate Multimedia',
  'Top Hat Studios Inc',
  'Weather Factory',
  'Xitilon',
  'astragon Entertainment',
  'ebihime',
  'mc2games',
  'Brightrock Games',
  'CFK Co. Ltd.',
  'Culture Select',
  'Deceptive Games',
  'Double Fine Productions',
  'Eidos Interactive',
  'Enlight Software Limited',
  'Firestoke',
  'Fishing Cactus',
  'Gamersky Games',
  'Handelabra Games Inc.',
  'HapGames',
  'HeartBeat Games',
  'Immanitas Entertainment GmbH',
  'Intragames',
  'Knuckle Cracker',
  'Minicactus Games',
  'Pathea Games',
  'Perp Games',
  'Playstation Publishing LLC',
  'Rake in Grass',
  'Reverb Triple XP',
  'Reverie World Studios',
  'Shiver Games',
  'Skystone Games',
  'Starni Games',
  'Stunlock Studios',
  'THE BROTHERHOOD',
  'TaleWorlds Entertainment',
  'Thermite Games',
  'Those Awesome Guys',
  'Virtual Arts Studio',
  '2tainment GmbH',
  'ARVORE Immersive Experiences',
  'Anarchy Enterprises',
  'Atomic Elbow',
  'BD Games',
  'Battlecruiser Games',
  'Big Fat Simulations Inc.',
  'Bleem.net',
  'Destructive Creations',
  'Digital Happiness',
  'EuroVideo Medien',
  'Flashbulb',
  'FromSoftware Inc.',
  'Funktronic Labs',
  'Hanako Games',
  'IV Productions',
  'Impossible Mystery Games',
  'Jagex',
  'Jesse Makkonen',
  'Koei Tecmo',
  'Koei Tecmo Games',
  'Kunos Simulazioni',
  'Kwalee Ltd',
  'Lion Castle Entertainment',
  'Ludosity',
  'M2H',
  'Marvelous Europe',
  'Mastiff',
  'Maximum Entertainment',
  'MiClos Studio',
  'MicroProse Software',
  'Mindscape',
  'Monster Couch',
  'MythicOwl',
  'New World Interactive',
  'No More Robots',
  'Offworld Industries Ltd.',
  'PGN Inc',
  'Paul Schneider',
  'Pixeljam',
  'Praxis Games',
  'Quantic Dream S.A.',
  'RuneStorm',
  'Running With Scissors',
  'SOEDESCO',
  'SUPERHOT Team',
  'Screenwave Media',
  'Snapshot Games Inc.',
  'Squanch Games Inc.',
  'Star Drifters',
  'Subterranean Games',
  'Tagstar Games',
  'Tequila Works',
  'Walkabout',
  'Wargaming Group Limited',
  'Warner Bros. Games',
  'Zenva',
  'Zodiac Interactive',
  'eigoMANGA',
  'nDreams',
];

export const generateDevelopers = async () => {
  const developerRepo = new DeveloperRepo(DeveloperModel);
  const props = developers.map((genre) => ({
    name: genre,
    slug: textUtils.generateSlug(genre),
  }));

  const promises = props.map((x) => developerRepo.createDeveloper(x));
  await Promise.all(promises);
  console.log('developers generated');
};
