import { GenreRepo } from '../genre/genreRepo';
import { GenreModel } from '../genre/model';
import { textUtils } from '../utils/textUtils';

const genres = [
  '1980s',
  '1990s',
  '2.5D',
  '2D',
  '2D Fighter',
  '2D Pixel',
  '2D Platformer',
  '2D RPG',
  '3D',
  '3D Battle',
  '3D Fighter',
  '3D Platformer',
  '3D Vision',
  '4 Player Local',
  '4X',
  '6DOF',
  'Abstract',
  'Action',
  'Action-Adventure',
  'Action Roguelike',
  'Action RPG',
  'Action RTS',
  'Addictive',
  'Adventure',
  'Adventure RPG',
  'Agriculture',
  'Alien Strategy',
  'Aliens',
  'All Individual Sports',
  'All Team Sports',
  'Alternate History',
  'Ambient',
  'America',
  'Anime',
  'Archery',
  'Arena Shooter',
  'Artificial Intelligence',
  'Assassin',
  'Asymmetric VR',
  'Asynchronous Multiplayer',
  'Atmospheric',
  'ATV',
  'Auto Battler',
  'Automation',
  'Automobile Sim',
  'Base Building',
  'Baseball',
  'Based On A Novel',
  'Basketball',
  'Battle Royale',
  "Beat 'em up",
  'Beautiful',
  'Bikes',
  'Board and Card',
  'Board Game',
  'Boxing',
  'Building',
  'Building and Automation',
  'Bullet Hell',
  'Bullet Time',
  'Capitalism',
  'Car Shooting',
  'Card Battler',
  'Card Game',
  'Cartoon',
  'Cartoon Fighting',
  'Cartoon Shooter',
  'Casual',
  'Casual Multiplayer',
  'Cats',
  'Character Action Game',
  'Character Customization',
  'Chess',
  'Choices Matter',
  'Choose Your Own Adventure',
  'Cinematic',
  'City Builder',
  'Class-Based',
  'Classic',
  'Clicker',
  'Co-op',
  'Co-op Adventure',
  'Co-op Base Building',
  'Co-op Board Game',
  'Co-op Campaign',
  'Co-op Card Game',
  'Co-op Deck Building',
  'Co-op Horror',
  'Co-op Open World',
  'Co-op Puzzle',
  'Co-op Robot',
  'Co-op RPG',
  'Co-op Sports',
  'Cold War',
  'Collectathon',
  'Collectible Card Game',
  'Colony Sim',
  'Colorful',
  'Combat',
  'Combat Racing',
  'Comedy',
  'Comic Book',
  'Comics, Horror',
  'Competitive',
  'Competitive FPS',
  'Conspiracy',
  'Controller',
  'Conversation',
  'Cooking',
  'Couch Co-op',
  'Crafting',
  'Creature Collector',
  'Crime',
  'CRPG',
  'Cult Classic',
  'Cute',
  'Cyberpunk',
  'Cycling',
  'Dark',
  'Dark Comedy',
  'Dark Fantasy',
  'Dark Humor',
  'Dating Sim',
  'Deckbuilding',
  'Demons',
  'Destruction',
  'Detective',
  'Difficult',
  'Dinosaur Shooting',
  'Dinosaur Simulator',
  'Dinosaurs',
  'Diplomacy',
  'Dog',
  'Dragons',
  'Drama',
  'Driving',
  'Dungeon Crawler',
  'Dungeons & Dragons',
  'Dynamic Narration',
  'Dystopian',
  'eBook, Fantasy',
  'eBook, Science Fiction',
  'eBooks',
  'Economy',
  'Education',
  'Emotional',
  'Epic',
  'Episodic',
  'Escape Room',
  'Experience',
  'Exploration',
  'Faith',
  'Family Friendly',
  'Fantasy',
  'Fantasy Board Game',
  'Fantasy Card Game',
  'Farming',
  'Farming Sim',
  'Fast-Paced',
  'Female Protagonist',
  'Fighting',
  'Fighting RPG',
  'First-Person',
  'First Person Adventure',
  'First Person Fighting',
  'First Person Horror',
  'First Person RPG',
  'Fishing',
  'Fishing and Hunting',
  'Flight',
  'Flight Simulator',
  'Flying Shooting',
  'FMV',
  'Football',
  'Football Simulation',
  'Foreign',
  'FPS',
  'Funny',
  'Funny Multiplayer',
  'Funny Physics',
  'Futuristic',
  'Gambling',
  'Game Development',
  'GameMaker',
  'God Game',
  'Golf',
  'Gothic',
  'Grand Strategy',
  'Great Soundtrack',
  'Grid-Based Movement',
  'Gun Customization',
  'Hack and Slash',
  'Hacking',
  'Hand-drawn',
  'Heist',
  'Hero Shooter',
  'Hex Grid',
  'Hidden Object',
  'Historical',
  'Horror',
  'Horror FPS',
  'Horror Puzzle',
  'Horses',
  'Hunting',
  'Idler',
  'Illuminati',
  'Immersive',
  'Immersive Sim',
  'Interactive Fiction',
  'Inventory Management',
  'Investigation',
  'Isometric',
  'Isometric RPG',
  'Jet',
  'JRPG',
  'Level Editor',
  'LGBTQ+',
  'Life Sim',
  'Linear',
  'Local Co-Op',
  'Local Multiplayer',
  'Logic',
  'Loot',
  'Looter Shooter',
  'Lore-Rich',
  'Lovecraftian',
  'Magic',
  'Management',
  'Mars',
  'Martial Arts',
  'Massively Multiplayer',
  'Match 3',
  'Mechs',
  'Medical Sim',
  'Medieval',
  'Medieval Strategy',
  'Memes',
  'Metroidvania',
  'Military',
  'Mini Golf',
  'Minigames',
  'Minimalist',
  'Mining',
  'MMORPG',
  'MMORPG Shooter',
  'MOBA',
  'Moddable',
  'Modern',
  'Motocross',
  'Motorbike',
  'Mouse only',
  'Movie',
  'Multiplayer',
  'Multiplayer Horror',
  'Multiplayer Hunting',
  'Multiplayer Racing',
  'Multiplayer Simulator',
  'Multiplayer Stealth',
  'Multiplayer Survival',
  'Multiplayer Trivia',
  'Multiplayer Wrestling',
  'Multiplayer Zombie',
  'Multiple Endings',
  'Music',
  'Music-Based Procedural Generation',
  'Mystery',
  'Mystery Dungeon',
  'Mystery Puzzle',
  'Mythology',
  'Narration',
  'Narrative',
  'Nature',
  'Naval',
  'Naval Combat',
  'Ninja',
  'Noir',
  'Nonlinear',
  'Nostalgia',
  'Offroad',
  'Old School',
  'On-Rails Shooter',
  'Online Co-Op',
  'Open World',
  'Open World Driving',
  'Open World Horror',
  'Open World Racing',
  'Open World Survival Craft',
  'Open World Zombie',
  'Otome',
  'Parkour',
  'Parody',
  'Party',
  'Party-Based RPG',
  'Perma Death',
  'Philosophical',
  'Physics',
  'Pinball',
  'Pirate MMO',
  'Pirates',
  'Pixel Graphics',
  'Pixel Horror',
  'Pixel Zombie',
  'Platformer',
  'Platformer Shooting',
  'Point & Click',
  'Point & Click Adventure',
  'Point & Click Horror',
  'Political',
  'Political Sim',
  'Politics',
  'Pool',
  'Post-apocalyptic',
  'Precision Platformer',
  'Procedural Generation',
  'Programming',
  'Psychedelic',
  'Psychological',
  'Psychological Horror',
  'Puzzle',
  'Puzzle Adventure',
  'Puzzle Platformer',
  'PvE',
  'PvP',
  'Quick-Time Events',
  'Racing',
  'Real-Time',
  'Real Time Tactics',
  'Real-Time with Pause',
  'Realistic',
  'Relaxing',
  'Relaxing Multiplayer',
  'Replay Value',
  'Resource Management',
  'Retro',
  'Rhythm',
  'Robots',
  'Roguelike',
  'Roguelike Deckbuilder',
  'Roguelite',
  'Roguevania',
  'Romance',
  'Rome',
  'RPG',
  'RPG Card Game',
  'RPG Racing',
  'RPG Story',
  'RPGs With Romance',
  'RTS',
  'Runner',
  'Sailing',
  'Sandbox',
  'Satire',
  'Scary Adventure',
  'Sci-fi',
  'Sci-Fi Simulation',
  'Sci-Fi Strategy',
  'Sci-Fi Survival',
  'Science',
  'Score Attack',
  "Shoot 'Em Up",
  'Shooter',
  'Short',
  'Side Scroller',
  'Silent Protagonist',
  'Simulation',
  'Simulation Racing',
  'Singleplayer',
  'Skateboarding',
  'Skating',
  'Skiing',
  'Sniper',
  'Snow',
  'Social Deduction',
  'Software',
  'Sokoban',
  'Solitaire',
  'Souls-like',
  'Soundtrack',
  'Space',
  'Space Horror',
  'Space RTS',
  'Space Sim',
  'Spaceships',
  'Spectacle fighter',
  'Spelling',
  'Split Screen',
  'Sports',
  'Sports and Racing',
  'Stealth',
  'Steampunk',
  'Story Puzzle',
  'Story Rich',
  'Strategy',
  'Strategy Board Game',
  'Strategy Card Game',
  'Strategy Puzzle',
  'Strategy RPG',
  'Stylized',
  'Submarine',
  'Superhero',
  'Superhero Flying',
  'Superhero RPG',
  'Supernatural',
  'Surreal',
  'Survival',
  'Survival Horror',
  'Survival MMO',
  'Swordplay',
  'Tabletop',
  'Tabletop Fantasy',
  'Tabletop RPG',
  'Tactical',
  'Tactical RPG',
  'Tactical Shooter',
  'Tanks',
  'Team-Based',
  'Tennis',
  'Text-Based',
  'Third Person',
  'Third-Person Shooter',
  'Thriller',
  'Time Attack',
  'Time Management',
  'Time Manipulation',
  'Time Travel',
  'Top-Down',
  'Top Down RPG',
  'Top-Down Shooter',
  'Touch-Friendly',
  'Tower Defense',
  'TrackIR',
  'Trading',
  'Trading Card Game',
  'Traditional Roguelike',
  'Train Simulator',
  'Trains',
  'Transhumanism',
  'Transportation',
  'Trivia',
  'Turn-Based',
  'Turn-Based Combat',
  'Turn Based RPG',
  'Turn-Based Strategy',
  'Turn-Based Tactics',
  'Tutorial',
  'Twin Stick Shooter',
  'Typing',
  'Underground',
  'Underwater',
  'Unforgiving',
  'Vampire',
  'Vampire RPG',
  'Vehicular Combat',
  'Vikings',
  'Villain Protagonist',
  'Violent',
  'Visual Novel',
  'Voxel',
  'VR',
  'Walking Simulator',
  'War',
  'War Strategy',
  'Wargame',
  'Well-Written',
  'Werewolves',
  'Western',
  'Word Game',
  'World War I',
  'World War II',
  'Wrestling',
  'WW1 Strategy',
  'WW2 Strategy',
  'Zombie Co-op Shooter',
  'Zombie Sniping',
  'Zombies',
];

export const generateGenres = async () => {
  const genreRepo = new GenreRepo(GenreModel);
  const props = genres.map((genre) => ({
    name: genre,
    slug: textUtils.generateSlug(genre),
  }));

  const promises = props.map((x) => genreRepo.createGenre(x));
  await Promise.all(promises);
  console.log('genres generated');
};
